// Single source of truth for all directions. Built from teghveer's résumé.

const RESUME = {
  name: 'Teghveer Singh Ateliey',
  short: 'Teghveer',
  location: 'Greater Toronto Area, Canada',
  role: 'Mechatronics Engineer',
  tagline: 'FPGAs, firmware, full-stack — engineer building across the stack.',
  summaryShort: 'I design the things that move signal between the physical and the digital — from VHDL on silicon, to firmware on spacecraft, to APIs in production.',
  summary: [
    "Technology touches every part of our lives. It brings us from A to B on roads, connects us to anyone else on the planet, and lets us design and imagine like never before.",
    "Ever since I was a little kid discovering the world, I knew I wanted to build the technology of tomorrow.",
    "Today I'm a Mechatronics Engineering student at McMaster, designing FPGAs at Evertz, writing payload firmware for a McMaster satellite, and developing vehicle software for a Formula Electric racecar.",
  ],
  links: {
    linkedin: 'linkedin.com/in/teghveerateliey',
    x: 'x.com/Tegh25',
    github: 'github.com/Tegh25',
    location: 'Toronto, Canada',
  },
  topSkills: ['C', 'C++', 'VHDL', 'Python', 'Linux', 'FreeRTOS'],
  languages: [
    { name: 'English', level: 'Native' },
    { name: 'Punjabi', level: 'Native' },
    { name: 'Hindi', level: 'Working' },
  ],
  skills: {
    'Hardware / FPGA': ['VHDL', 'Vivado', 'Integrated Logic Analyzer', 'Zynq 7000', 'STM32', 'SPI / I²C', 'ADC128S022'],
    'Firmware / Embedded': ['C', 'C++', 'FreeRTOS', 'FreeAct', 'OpenOCD', 'STLink', 'CMake', 'Active Object'],
    'Software': ['Python', 'React', 'GraphQL', 'Node', 'Bash', 'Docker', 'Git', 'C#/.NET'],
    'Signal & Video': ['JPEG-XS', 'SDI', 'Ethernet/IP', 'Wireshark', 'PRISM', 'DekTek', 'Phabrix'],
    'Tools': ['MATLAB', 'Simulink', 'DataDog', 'DBeaver', 'Azure'],
  },
  projects: [
    {
      id: 'evertz',
      slug: 'evertz',
      company: 'Evertz',
      role: 'FPGA Design Engineer',
      period: 'Jan 2025 — Present',
      location: 'Markham, ON',
      status: 'ongoing',
      tag: 'BROADCAST',
      color: '#60a5fa',
      domain: 'High-speed digital logic for video, audio, and Ethernet/IP systems at a world-leading broadcast firm.',
      oneLiner: 'Writing VHDL for broadcast FPGAs. Designed a JPEG-XS analyzer that cut PM team analysis time by 60%.',
      stack: ['VHDL', 'Vivado', 'C++', 'Python 3.11', 'Docker', 'JPEG-XS'],
      metrics: [
        { value: '60%', label: 'analysis time reduction' },
        { value: '2160p', label: 'format support shipped' },
        { value: '10+', label: 'FPGA pipeline bugs fixed' },
      ],
      impact: [
        'Designed a JPEG-XS stream analysis tool that automated multi-step workflows, reducing PM team analysis time by 60%.',
        'Migrated legacy Python 2 analysis scripts to Python 3.11 and containerized with Docker — improved accessibility and reliability across engineering teams.',
        'Diagnosed and resolved multiple FPGA video-pipeline bugs, including scaler artifacts and PID mapping issues.',
        'Led lip-sync delay testing by designing a mathematical model that solved encoder/decoder latency across multiple devices.',
        'Developed and tested VHDL logic for encoder modules — contributing to future support for 2160p23.98 and 2160p29.97 formats.',
        'Identified root causes and coordinated fixes for edge-case bugs (frame rate switching, QSFP failure) shipped in firmware builds.',
        'Improved third-party audio stream decoding by fixing buffer-depth issues, restoring audio fidelity.',
      ],
    },
    {
      id: 'preset',
      slug: 'preset-satellite',
      company: 'McMaster Interdisciplinary Satellite Team',
      role: 'Payload Firmware Specialist',
      period: 'Sep 2023 — Present',
      location: 'Hamilton, ON',
      status: 'ongoing',
      tag: 'SPACE',
      color: '#a78bfa',
      domain: 'Firmware autonomously controlling scientific instruments aboard the PRESET satellite — follow-up to the successful NEUDOSE mission.',
      oneLiner: 'Real-time pub/sub messaging for flight-critical systems on a satellite, on FreeRTOS + FreeAct.',
      stack: ['C', 'FreeRTOS', 'FreeAct', 'Zynq 7000', 'SPI', 'Active Object'],
      metrics: [
        { value: '10', label: 'observers per channel' },
        { value: '8', label: 'ADC channels per device' },
        { value: '100ms', label: 'telemetry polling floor' },
      ],
      impact: [
        'Designed and implemented a real-time publish-subscribe messaging system with 3 observer types (listeners, subscribers, message subscribers) and priority inheritance for deterministic message delivery.',
        'Architected thread-safe communication infrastructure using mutex protection and a Virtual Distributed Event Dispatcher (VDED) pattern.',
        'Built an autonomous ADC telemetry system polling multiple analog sensors at configurable intervals (100–300ms) using timer-driven Active Object architecture.',
        'Integrated multi-layer hardware abstraction connecting ADC128S022 devices through SPI to the real-time data distribution system.',
        'Designed the Firmware Block Diagram for all processor and hardware modules in the payload subsystem.',
        'Adapted and ported the SPI driver from the previous NEUDOSE mission to the new Zynq 7000 processing unit.',
      ],
    },
    {
      id: 'formula',
      slug: 'formula-electric',
      company: 'MAC Formula Electric',
      role: 'Vehicle Software Developer',
      period: 'Oct 2021 — Present',
      location: 'Hamilton, ON',
      status: 'ongoing',
      tag: 'MOTORSPORT',
      color: '#f97316',
      domain: 'Software and vehicle controls for an electric Formula racecar. DevOps, infrastructure, and C++.',
      oneLiner: 'Translated a Simulink vehicle dynamics model into C++ firmware; built the build/flash pipeline for the whole team.',
      stack: ['C++', 'STM32', 'Simulink', 'CMake', 'OpenOCD', 'Docker', 'Bash'],
      metrics: [
        { value: '4.5y', label: 'team tenure' },
        { value: '1', label: 'custom build pipeline' },
        { value: '∞', label: 'flashes survived' },
      ],
      impact: [
        'Engineered a C++ translation of a Simulink-based vehicle dynamics model — improved real-time simulation accuracy and firmware integration.',
        'Optimized building and flashing process for front-controller firmware using CMake, STLink, and Docker.',
        'Implemented OpenOCD enabling on-chip debugging and live expressions in VS Code for STM32 microcontrollers.',
        'Developed a versatile Bash script to automate Git checkout and build processes — enabled seamless project compilation across platforms.',
        'Coordinated with the team to configure the thermal management system of the car.',
      ],
    },
    {
      id: 'td-swe',
      slug: 'td-bank-swe',
      company: 'TD Bank',
      role: 'Software Engineer Intern',
      period: 'May — Aug 2023',
      location: 'Toronto, ON',
      status: 'past',
      tag: 'FINTECH',
      color: '#22c55e',
      domain: "Platforms & Technologies — developed two primary APIs and a front-end microapp on TD's AMCB side.",
      oneLiner: 'GraphQL queries, React microapps, and Party API fixes across a multi-microapp banking platform.',
      stack: ['GraphQL', 'React', 'react-bootstrap', 'REST', 'Agile'],
      metrics: [
        { value: '2', label: 'primary APIs touched' },
        { value: '3', label: 'microapps shipped' },
      ],
      impact: [
        'Crafted GraphQL POST request query to obtain party information for US-branch customers.',
        'Utilized react-bootstrap to develop a help-menu component that displays PDF modals to users.',
        'Enabled the Host database to receive selective data-field updates, increasing request efficiency.',
        'Added app functionality to subscribe to events published by other microapps and redirect accordingly.',
        'Prevented changes to certain fields when updating parties in PATCH requests.',
        'Created local setup guides to improve the onboarding process for future developers.',
      ],
    },
    {
      id: 'td-bsa',
      slug: 'td-bank-bsa',
      company: 'TD Bank',
      role: 'Business Systems Analyst Intern',
      period: 'May — Aug 2022',
      location: 'Toronto, ON',
      status: 'past',
      tag: 'DEVOPS',
      color: '#14b8a6',
      domain: "Enterprise Delivery Pipeline (EDP) Cloud & DevOps — monitoring, incident response, pipeline tooling.",
      oneLiner: 'Documented 22+ pipeline FAQs as KB articles, refactored a reporting dashboard from Jinja2 to React.',
      stack: ['React', 'Jinja2', 'SQL', 'DataDog', 'Azure', 'DBeaver'],
      metrics: [
        { value: '22+', label: 'incidents → KB articles' },
        { value: '100+', label: 'aged incidents closed' },
      ],
      impact: [
        'Led the effort to document common user incidents in KB articles — foundation for a developer-help chatbot.',
        "Refactored KPI's Docker Reports page to use React components instead of Jinja2 HTML templates.",
        'Enabled DataDog alerts and incident creation for general monitoring metrics, LDAP/VDSI issues, and node availability.',
        'Fixed an Azure ASE malcode tagging issue that was charging wrong enterprises for ASE use.',
        'Enabled the KPI project to read from the OBOE SQL database for onboarding reporting in DEV and PROD.',
      ],
    },
    {
      id: 'design-league',
      slug: 'design-league',
      company: 'McMaster Design League',
      role: 'VP Sponsorship → Outreach Specialist',
      period: 'Oct 2021 — Apr 2024',
      location: 'Hamilton, ON',
      status: 'past',
      tag: 'LEADERSHIP',
      color: '#ec4899',
      domain: 'Community building, sponsorship, and event ops for design & CAD competitions at McMaster.',
      oneLiner: 'Co-led a 9-person team, secured $8K in sponsorship, ran design competitions for 560+ participants.',
      stack: ['Leadership', 'Sponsorship', 'Event Ops'],
      metrics: [
        { value: '$8K', label: 'sponsorship secured' },
        { value: '560+', label: 'participants' },
        { value: '80+', label: 'institutions' },
      ],
      impact: [
        'Co-led a team of 9 to secure $8,000 in monetary and in-kind sponsorship from MDA, SolidWorks, Relevant Bits, and more.',
        'Organized two design competitions with 560+ participants representing 80+ institutions across 77 teams.',
        'Networked with 23 industry professionals as mentors, speakers, and judges.',
        'Awarded Outreach Specialist of the Month for top team contribution and recruitment.',
      ],
    },
    {
      id: 'aerospace',
      slug: 'aerospace',
      company: 'McMaster Aerospace Team',
      role: 'Structures Team Member',
      period: 'Aug 2022 — Jun 2023',
      location: 'Hamilton, ON',
      status: 'past',
      tag: 'AEROSPACE',
      color: '#64748b',
      oneLiner: 'Mechanical design of fuselage, payload bay, and support structures for a student-built aircraft.',
      stack: ['CAD', 'Mech Design'],
      impact: [
        'Designing mechanical structure of the aircraft — fuselage, payload bay, support structures.',
        'Developed a conceptual design to mount horizontal and vertical stabilizers while decreasing wake.',
        'Proposed a landing-gear configuration optimizing CG stability vs. cost and construction complexity.',
      ],
    },
    {
      id: 'cyber',
      slug: 'cyber-defence',
      company: 'Glenlawn Collegiate — Cyber Defence',
      role: 'Team Lead',
      period: 'Oct 2018 — Jun 2021',
      location: 'Winnipeg, MB',
      status: 'past',
      tag: 'SECURITY',
      color: '#eab308',
      oneLiner: '1st place out of 27 teams in the Canadian Cyber Defence Challenge (high school division).',
      stack: ['Linux Hardening', 'Cisco', 'Packet Tracer', 'Kali'],
      impact: [
        'Led team gcilion1 to first place out of 27 teams in the Canadian Cyber Defence Challenge.',
        'Specialized in hardening Linux systems, networking Cisco routers, and Packet Tracer.',
        'Competed in CyberPatriot, PicoCTF, Canadian Computing Contest, and the U Manitoba CS fair.',
      ],
    },
    {
      id: 'robotics',
      slug: 'robotics-club',
      company: 'Glenlawn Collegiate — Robotics Club',
      role: 'Founder & Leader',
      period: 'Sep 2019 — Jun 2021',
      location: 'Winnipeg, MB',
      status: 'past',
      tag: 'CLUB',
      color: '#06b6d4',
      oneLiner: 'Founded the robotics club from scratch — 10 members, two RC robots, Skills Manitoba.',
      stack: ['Leadership', 'Robotics'],
      impact: [
        'Founded and organized the robotics club at my high school starting with ten members.',
        'Researched and initiated club projects and managed subteams.',
        'Built two remote-controlled robots for the Skills Manitoba competition.',
      ],
    },
  ],
  education: [
    {
      school: 'McMaster University',
      degree: 'B.Eng. Mechatronics Engineering & Society',
      period: '2021 — 2028',
      location: 'Hamilton, ON',
    },
    {
      school: 'Glenlawn Collegiate Institute',
      degree: 'High School Diploma',
      period: '2017 — 2021',
      location: 'Winnipeg, MB',
    },
    {
      school: "The Duke of Edinburgh's International Award",
      degree: 'Silver & Bronze',
      period: '2017 — 2025',
      location: 'Canada',
    },
  ],
  awards: [
    "Duke of Edinburgh International Award — Silver",
    "Duke of Edinburgh International Award — Bronze",
    "Bulla Arts International Leadership Award",
    "The McMaster University Award of Excellence",
    "Jerry Kruk Memorial Scholarship",
  ],
  certifications: [
    'Simulink Onramp',
    'Control Design Onramp with Simulink',
    'MATLAB Onramp',
    'C# and .NET Essential Training',
    'WHMIS',
  ],
};

window.RESUME = RESUME;
